version: '3.8'

services:
  frontend:
    image: nikkeyl:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 60s
        failure_action: pause

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
