name: Deploy to Production Swarm

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      tag: ${{ steps.image.outputs.TAG }}
      image_name: ${{ steps.image.outputs.IMAGE_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DC_PAT }}

      - name: Define image tag and name
        id: image
        run: |
          echo "TAG=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${{ github.repository_owner }}/nikkeyl" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.image.outputs.IMAGE_NAME }}:${{ steps.image.outputs.TAG }},${{ steps.image.outputs.IMAGE_NAME }}:latest

  deploy:
    name: Deploy

    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: [build]

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH and Swarm update
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            NEW_IMAGE_NAME="${{ needs.build.outputs.image_name }}"
            NEW_TAG="${{ needs.build.outputs.tag }}"

            echo "Moving to project directory..."

            cd /nikkeyl

            sed -i "s|image: [^:]*:[^|]*|image: ${NEW_IMAGE_NAME}:${NEW_TAG}|" docker-compose.yml

            echo "Starting Swarm deployment with image: ${NEW_IMAGE_NAME}:${NEW_TAG}"

            docker stack deploy -c docker-compose.yml nikkeyl_stack

            echo "Deployment finished. Docker Swarm will now perform a rolling update."

            sleep 30

            docker service ps nikkeyl_stack_web --no-trunc
